_wandb:
    value:
        cli_version: 0.19.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": validation_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.9.18
        t:
            "1":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 103
                - 105
            "2":
                - 1
                - 9
                - 11
                - 49
                - 55
                - 71
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.18
            "5": 0.19.7
            "6": 4.33.1
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
